# Generated by Django 4.2.6 on 2023-10-12 01:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(limit_value=5, message='El nombre de usuario debe tener al menos 5 caracteres.')])),
                ('email', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(limit_value=5, message='Su contraseña debe tener al menos 5 caracteres.')])),
            ],
        ),
    ]
