# Generated by Django 4.2.6 on 2023-10-13 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_mascota_mascotacategoria_delete_usuario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mascotacategoria',
            options={'verbose_name': 'categoría de mascotas', 'verbose_name_plural': 'categorias de mascotas'},
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='unidad_de_medida',
            new_name='raza',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='precio',
        ),
    ]
