# Generated by Django 4.2.6 on 2023-10-25 18:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0003_alter_mascotacategoria_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='fecha_actualizacion',
        ),
        migrations.AddField(
            model_name='mascota',
            name='fecha_nacimiento',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='fecha de nacimiento'),
        ),
    ]
