# Generated by Django 4.2.6 on 2023-10-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0004_remove_mascota_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
